version: "3.9"

services:
  app:
    build:
      args:
        APP_CONTEXT_PATH: $APP_CONTEXT_PATH
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: $QUANTIPIN_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/app/Dockerfile
    container_name: quantipin_app
    depends_on:
      - mysql
    environment:
      DEBUG_LOG: /var/log/app.log
      DEFAULT_LOCALE: "en_US"
      ENVIRONMENT: "development"
      ERROR_REPORTING: "true"
      FORCE_HTTPS: "false"
      SITE_NAME: "Quanti PIN"
    networks:
      - external
      - internal
    volumes:
      - $APP_DIRECTORY:/home/dockeruser/app
      - $DOCKER_DIRECTORY/images/app/php.ini:/usr/local/etc/php/php.ini
      - $APP_LOG_DIRECTORY:/var/log

  http-proxy:
    build:
      args:
        DOCKER_IMAGE_CONTEXT_PATH: $DOCKER_IMAGE_CONTEXT_PATH
        GROUP_ID: $GROUP_ID
        USER_ID: $USER_ID
      context: $QUANTIPIN_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/http-proxy/Dockerfile
    container_name: quantipin_http-proxy
    depends_on:
      - app
    networks:
      - external
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - $DOCKER_DIRECTORY/images/http-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - $HTTP_PROXY_LOG_DIRECTORY:/var/log/nginx

  mysql:
    build:
      context: $QUANTIPIN_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/mysql/Dockerfile
    container_name: quantipin_mysql
    environment:
      MYSQL_DATABASE: "quantipin"
      MYSQL_PASSWORD: "quantipin"
      MYSQL_ROOT_PASSWORD: "quantipin"
      MYSQL_USER: "quantipin"
    networks:
      - internal
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql
      - $DOCKER_DIRECTORY/images/mysql/custom.my.cnf:/etc/mysql/conf.d/custom.my.cnf

  adminer:
    build:
      context: $QUANTIPIN_DIRECTORY
      dockerfile: $DOCKER_DIRECTORY/images/adminer/Dockerfile
    container_name: quantipin_adminer
    depends_on:
      - mysql
    networks:
      - external
      - internal

networks:
  internal:
  external:

volumes:
  mysql:
